## Jekyll configuration

# Include pages
include: ['_pages']
permalink: pretty

# Site settings
title: Lanlords Docs
description: >-
  Een verzameling van de installatie instructies van de games,
  informatie over de LAN zelf en oplossingen voor veelvoorkomende problemen.
baseurl: "/"
url: "https://docs.lanlords.nl"

# Build settings
remote_theme: pmarsceill/just-the-docs
plugins:
  - jekyll-feed

# Header navigation
aux_links:
  "Discord":
    - "https://discord.lanlords.nl"
  "Website":
    - "http://www.lanlords.nl"

# Content variables
games:
  bf1942:
    download: "https://f002.backblazeb2.com/file/lanlords/games/bf1942.zip"
    version:  v1.61b
  bf2:
    download: "https://f002.backblazeb2.com/file/lanlords/games/bf2.zip"
    version:  v1.50
  bf3:
    download: "https://f002.backblazeb2.com/file/lanlords/games/bf3.zip"
    version:  '-'
  bfbc2:
    download: "https://f002.backblazeb2.com/file/lanlords/games/bfbc2.zip"
    version:  '-'
  cod2:
    download: "https://f002.backblazeb2.com/file/lanlords/games/cod2.zip"
    version:  v1.3
  cod4:
    download: "https://f002.backblazeb2.com/file/lanlords/games/cod4.zip"
    version:  v1.7
  cod5:
    download: "https://f002.backblazeb2.com/file/lanlords/games/cod5.zip"
    version:  v1.7
  csgo:
    version:  'laatste Steam versie'
  css:
    download: "https://f002.backblazeb2.com/file/lanlords/games/css.zip"
    mirror:   "http://lanlords.nehox.eu:8888/Counter-Strike%20Source.zip"
    version:  '-'
  fo2:
    download: "https://f002.backblazeb2.com/file/lanlords/games/fo2.zip"
    mirror:   "http://lanlords.nehox.eu:8888/FlatOut%202.zip"
    version:  '-'
  tf2:
    version:  'laatste Steam versie'
