## Jekyll configuration

# Include pages
permalink: pretty

# Site settings
title: Lanlords Docs
description: >-
  Een verzameling van de installatie instructies van de games,
  informatie over de LAN zelf en oplossingen voor veelvoorkomende problemen.
baseurl: "/"
remote_theme: just-the-docs/just-the-docs
url: "https://docs.lanlords.nl"

# Build settings
plugins:
  - jekyll-feed

# Header navigation
aux_links:
  "Discord":
    - "https://discord.lanlords.nl"
  "Website":
    - "http://www.lanlords.nl"

# Content variables
data:
  bf1942:
    download: "https://download.fieldfuckers.nl/games/bf1942.zip"
    version:  v1.61b
  bf2:
    download: "https://download.fieldfuckers.nl/games/bf2.zip"
    version:  v1.50
  bf3:
    download: "https://download.fieldfuckers.nl/games/bf3.zip"
    version:  '-'
  bf4:
    download: "https://download.fieldfuckers.nl/games/bf4.zip"
    version:  '-'
  bfbc2:
    download: "https://download.fieldfuckers.nl/games/bfbc2.zip"
    version:  '-'
  bt1944:
    version:  'laatste Steam versie'
  cmw:
    version:  'laatste Steam versie'
  cod2:
    download: "https://download.fieldfuckers.nl/games/cod2.zip"
    version:  v1.3
  cod4:
    download: "https://download.fieldfuckers.nl/games/cod4.zip"
    version:  v1.7
  cod5:
    download: "https://download.fieldfuckers.nl/games/cod5.zip"
    version:  v1.7
  cs2:
    version:  'laatste Steam versie'
  css:
    download: "https://download.fieldfuckers.nl/games/css.zip"
    version:  '-'
  fo2:
    download: "https://download.fieldfuckers.nl/games/fo2.zip"
    version:  '-'
  hli:
    version:  'laatste Steam versie'
  tf2:
    version:  'laatste Steam versie'

collections:
  games:
    permalink: "/:collection/:path/"
    output: true

just_the_docs:
  collections:
    games:
      name: Games
