## Jekyll configuration

# Include pages
include: ['_pages']
permalink: pretty

# Site settings
title: Lanlords Docs
description: >-
  Een verzameling van de installatie instructies van de games,
  informatie over de LAN zelf en oplossingen voor veelvoorkomende problemen.
baseurl: "/"
url: "https://docs.lanlords.nl"

# Build settings
remote_theme: pmarsceill/just-the-docs
plugins:
  - jekyll-feed

# Header navigation
aux_links:
  "Discord":
    - "https://discord.lanlords.nl"
  "Download":
    - "https://download.fieldfuckers.nl"
  "Website":
    - "http://www.lanlords.nl"

# Content variables
games:
  bf1942:
    download: "http://download.fieldfuckers.nl/file/bf1942"
    version:  v1.61b
  bf2:
    download: "http://download.fieldfuckers.nl/file/bf2"
    version:  v1.50
  bf3:
    download: "http://download.fieldfuckers.nl/file/bf3"
    version:  '-'
  bfbc2:
    download: "http://download.fieldfuckers.nl/file/bfbc2"
    version:  '-'
  cod2:
    download: "http://download.fieldfuckers.nl/file/cod2"
    version:  v1.3
  cod4:
    download: "http://download.fieldfuckers.nl/file/cod4"
    version:  v1.7
  cod5:
    download: "http://download.fieldfuckers.nl/file/cod5"
    version:  v1.7
  csgo:
    version:  'laatste Steam versie'
  css:
    download: "http://download.fieldfuckers.nl/file/css"
    version:  '-'
  fo2:
    download: "http://download.fieldfuckers.nl/file/fo2"
    version:  '-'
  tf2:
    version:  'laatste Steam versie'
