## Jekyll configuration

# Include pages
include: ['_pages']
permalink: pretty

# Site settings
title: Lanlords Docs
description: >-
  Een verzameling van de installatie instructies van de games,
  informatie over de LAN zelf en oplossingen voor veelvoorkomende problemen.
baseurl: "/"
url: "https://docs.lanlords.nl"

# Build settings
remote_theme: pmarsceill/just-the-docs
plugins:
  - jekyll-feed

# Header navigation
aux_links:
  "Discord":
    - "https://discord.lanlords.nl"
  "Radio":
    - "https://radio.lanlords.nl"
  "Website":
    - "http://www.lanlords.nl"

# Content variables
games:
  bf1942:
    download: "https://lanlords-files.fieldfuckers.nl/file/lanlords/games/bf1942.zip"
    version: v1.61b
  bf2:
    version: ntb
  bfbc2:
    version: ntb
  cod2:
    download: "https://lanlords-files.fieldfuckers.nl/file/lanlords/games/cod2.zip"
    version: v1.3
  cod4:
    download: "https://lanlords-files.fieldfuckers.nl/file/lanlords/games/cod4.zip"
    version: v1.7
  cod5:
    version: v1.5
  csgo:
    version: 'laatste Steam versie'
  css:
    version: ntb
  tf2:
    version: 'laatste Steam versie'
